<#
.SYNOPSIS
    Dev Harness — cross-platform init script (PowerShell).
.DESCRIPTION
    Installs dependencies, verifies the setup, and starts the dev server
    for the detected project stack.
.NOTES
    Generated by Dev Harness v5.1.0 for node.
#>

$ErrorActionPreference = "Stop"
$HarnessVersion = "5.1.0"
$Stack = "node"
$StackLabel = "Node.js"

Write-Host "=== $StackLabel — Dev Harness ===" -ForegroundColor Cyan
Write-Host ""

# ── Install ──────────────────────────────────────────────────────────────────
Write-Host "Installing dependencies..." -ForegroundColor Yellow

switch ($Stack) {
  "python" {
    python -m pip install -e ".[dev]" 2>$null
    if ($LASTEXITCODE -ne 0) { pip install -e ".[dev]" }
  }
  "node" {
    npm install
  }
  "go" {
    go mod download
  }
  "rust" {
    cargo build
  }
  "java" {
    mvn install -DskipTests
  }
  "kotlin" {
    ./gradlew build
  }
  "dotnet" {
    dotnet restore
  }
  "c" {
    # C toolchain — requires gcc/cmake (install via system package manager)
    cmake --version 2>$null
    if ($LASTEXITCODE -ne 0) { Write-Host "cmake not found — install CMake + a C compiler" -ForegroundColor Yellow }
  }
  "cpp" {
    # C++ toolchain — requires g++/cmake
    cmake --version 2>$null
    if ($LASTEXITCODE -ne 0) { Write-Host "cmake not found — install CMake + a C++ compiler" -ForegroundColor Yellow }
  }
  "matlab" {
    # MATLAB — no install step; verify matlab is on PATH at verify stage
  }
  "vhdl" {
    # VHDL — GHDL is the common open-source simulator
    ghdl --version 2>$null
    if ($LASTEXITCODE -ne 0) { Write-Host "ghdl not found — install GHDL for VHDL simulation" -ForegroundColor Yellow }
  }
  "verilog" {
    # Verilog/SystemVerilog — Icarus Verilog is the common open-source simulator
    iverilog -V 2>$null
    if ($LASTEXITCODE -ne 0) { Write-Host "iverilog not found — install Icarus Verilog" -ForegroundColor Yellow }
  }
  Default {
    Write-Host "No install command configured for $Stack" -ForegroundColor Yellow
  }
}

Write-Host "  ✓ Dependencies installed" -ForegroundColor Green

# ── Verify ───────────────────────────────────────────────────────────────────
Write-Host "`nVerifying setup..." -ForegroundColor Yellow

switch ($Stack) {
  "python" { python -m pytest --version }
  "node"   { npm test }
  "go"     { go test ./... }
  "rust"   { cargo test }
  "java"   { mvn test }
  "kotlin" { ./gradlew test }
  "dotnet" { dotnet build }
  "c"      { cmake --version }
  "cpp"    { cmake --version }
  "matlab" { matlab -batch "disp('matlab ok')" }
  "vhdl"   { ghdl --version }
  "verilog"{ iverilog -V }
  Default { Write-Host "No verify command configured for $Stack" -ForegroundColor Yellow }
}

Write-Host "  ✓ Setup verified" -ForegroundColor Green

# ── Start ────────────────────────────────────────────────────────────────────
Write-Host "`nSetup complete. Run: dev-harness phase define" -ForegroundColor Cyan
